---
apiVersion: v1
kind: Namespace
metadata:
  name: tech-challenge

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tech-challenge
data:
  RabbitMQ__HostName: "rabbitmq"
  SqlServer__HostName: "sqlserver"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: tech-challenge
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SA_PASSWORD
          value: "Ad4c5a@!!56"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: tech-challenge
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: techchallenge4-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RabbitMQ__HostName
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RabbitMQ__HostName
        - name: SqlServer__HostName
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SqlServer__HostName
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: tech-challenge
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumidor
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumidor
  template:
    metadata:
      labels:
        app: consumidor
    spec:
      containers:
      - name: consumidor
        image: techchallenge4-consumidor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RabbitMQ__HostName
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RabbitMQ__HostName
        - name: SqlServer__HostName
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SqlServer__HostName
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: consumidor
  namespace: tech-challenge
spec:
  selector:
    app: consumidor
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
